### PR TITLE
mapCommentType is block for CSS files

### PR DESCRIPTION
**Pull request by jamesarosen**
See https://github.com/ef4/broccoli-sourcemap-concat/issues/37

### CODE REVIEW

**Comment by jamesarosen** [comment]
Some caveats:

 1. `mapCommentType` is still dictated purely by this library and cannot be changed by a client. This can easily be fixed by changing the line to `opts.mapCommentType || ...`, but I wanted to make the smallest change that could possibly work.
 1. `mapCommentType` is dependent upon CSS files being named `*.css`
 1. `mapCommentType` is CSS-aware, but `mapFile` is not

**Comment by stefanpenner** [comment]
> mapCommentType is dependent upon CSS files being named *.css

this seems reasonable

**Comment by stefanpenner** [comment]
@rwjblue @ef4 r?

**Comment by ef4** [comment]
The upstream caller (ember-cli) always knows what kind of files it's concatenating. I would rather have it pass an appropriate option than try to autodetect based on extensions.

**Comment by jamesarosen** [comment]
The *immediate* upstream caller is ef4/broccoli-sourcemap-concat. Is that where you'd like a PR?

**Comment by ef4** [comment]
Yes, please. Or perhaps https://github.com/ember-cli/broccoli-concat instead. @stefanpenner, is that practical to use for everybody at this point?

**Comment by jamesarosen** [comment]
Ember-CLI 1.13 hasn't been ported to broccoli-concat yet.

Broccoli-Concat also says it doesn't yet support sourcemaps.

**Comment by rwjblue** [comment]
> Broccoli-Concat also says it doesn't yet support sourcemaps.

From the title of the [README](https://github.com/ember-cli/broccoli-concat#broccoli-concatenator-that-generates--propagates-sourcemaps):

> Broccoli concatenator that generates & propagates sourcemaps
>
> This filter is designed to be fast & good enough. It can generates source maps substantially faster than you'll get via mozilla/source-map, because it's special-cased for straight line-to-line contenation.

**Comment by jamesarosen** [comment]
I could've sworn there was an open issue/PR that was basically "Broccoli doesn't do sourcemaps right yet, so `¯\_(ツ)_/¯`." But I can't find it, so :tada:

**Comment by stefanpenner** [comment]
We should switch to broccoli-concat for 1.13. Although we will hopefully cutover to 2x soon

**Comment by jamesarosen** [comment]
@stefanpenner do you want me to make a go at that? Any advice?

**Comment by stefanpenner** [comment]
@jamesarosen if you want, whats preventing you from using the 2.x betas?

**Comment by jamesarosen** [comment]
@stefanpenner we're on Ember 1.13. I don't know if those are compatible.

**Comment by stefanpenner** [comment]
> @stefanpenner we're on Ember 1.13. I don't know if those are compatible.
>  Show all checks

Yes they are compatible, the only difference is 2.x bundles new code.

I would recommend upgrading, I do not believe we will back port this change.

**Comment by dfreeman** [comment]
Did an issue/PR for this ever make it to broccoli-concat? I don't see one, but wanted to make sure there aren't plans to handle this in a different layer that have come together since this thread last had activity.

**Comment by jamesarosen** [comment]
I just opened https://github.com/ember-cli/broccoli-concat/issues/58

**Pull request closed without merging**
